name: RoleplayChat
main: com.normarthehero.plugin.RoleplayPlugin
version: 1.0
commands:
  roleplay:
    description: Enable roleplay chat
    usage: /roleplay
    aliases: [rp]
    permission: roleplay.use
    permission-message: Missing permission.