name: RoleplayChat
main: com.normarthehero.plugin.RoleplayPlugin
version: 0.2
commands:
  roleplay:
    description: Roleplay with friends!
    usage: /roleplay
    aliases: [rp]
    permission: roleplay.use
    permission-message: Hey! You can't do that!